/* eslint-disable no-unused-vars */
const candidates_list = {
  protagonists_data: [
    {
      pic: require("./assets/saitama.jpg"),
      name: "Saitama",
      partido: "Associação dos heróis por diversão",
      number: 99,
      votes: 0,
    },
    {
      pic: require("./assets/tanjiro.jpg"),
      name: "Tanjiro",
      partido: "Caçadores de Demônios",
      number: 66,
      votes: 0,
    },
    {
      pic: require("./assets/naruto.jpg"),
      name: "Naruto",
      partido: "Vila de Konoha",
      number: 50,
      votes: 0,
    },
    {
      pic: require("./assets/goku.jpg"),
      name: "Goku",
      partido: "Saiyajins Terráqueos",
      number: 10,
      votes: 0,
    },
    {
      pic: require("./assets/luffy.jpg"),
      name: "Luffy",
      partido: "Os piratas",
      number: 41,
      votes: 0,
    },
    {
      pic: require("./assets/gon.jpg"),
      name: "Gon Freecss",
      partido: "The Hunters",
      number: 25,
      votes: 0,
    },
    {
      pic: require("./assets/edward.jpg"),
      name: "Edward Cullen",
      partido: "Twilighters",
      number: 24,
      votes: 0,
    },
    {
      pic: require("./assets/tobey.jpg"),
      name: "Spider-Man (Tobey-Maguire)",
      partido: "Spider-verse",
      number: 70,
      votes: 0,
    },
    {
      pic: require("./assets/django.jpg"),
      name: "Django",
      partido: "Freedom",
      number: 35,
      votes: 0,
    },
    {
      pic: require("./assets/harry.jpg"),
      name: "Harry Potter",
      partido: "The Order of the Phoenix",
      number: 33,
      votes: 0,
    },
    {
      pic: require("./assets/luke.jpg"),
      name: "Luke Skywalker",
      partido: "The Jedi Order",
      number: 55,
      votes: 0,
    },
    {
      pic: require("./assets/alita.jpg"),
      name: "Alita",
      partido: "The robot army",
      number: 38,
      votes: 0,
    },
    {
      pic: require("./assets/eleven.jpg"),
      name: "Eleven",
      partido: "The 11 Project",
      number: 11,
      votes: 0,
    },
  ],

  antagonists_data: [
    {
      pic: require("./assets/garou.jpg"),
      name: "Garou",
      partido: "The Wannabe Monsters",
      number: 999,
      votes: 0,
    },
    {
      pic: require("./assets/vader.jpg"),
      name: "Darth Vader",
      partido: "The Empire",
      number: 500,
      votes: 0,
    },
    {
      pic: require("./assets/madara.jpg"),
      name: "Uchiha Madara",
      partido: "Tsukoyomi Lovers",
      number: 675,
      votes: 0,
    },
    {
      pic: require("./assets/reverse.jpg"),
      name: "Reverse Flash",
      partido: "Anti Speedsters",
      number: 998,
      votes: 0,
    },
    {
      pic: require("./assets/homelander.jpg"),
      name: "Homelander",
      partido: "The 7",
      number: 620,
      votes: 0,
    },
    {
      pic: require("./assets/vecna.jpg"),
      name: "Vecna",
      partido: "01 Project",
      number: 111,
      votes: 0,
    },
    {
      pic: require("./assets/joker.jpg"),
      name: "Joker",
      partido: "Psycho Buddies",
      number: 123,
      votes: 0,
    },
    {
      pic: require("./assets/evilmorty.jpg"),
      name: "Evil Morty",
      partido: "Finite curve of evil",
      number: 456,
      votes: 0,
    },
    {
      pic: require("./assets/thanos.jpg"),
      name: "Thanos",
      partido: "Balance buddies",
      number: 800,
      votes: 0,
    },
    {
      pic: require("./assets/blacknoir.jpg"),
      name: "Black Noir (Comics)",
      partido: "The Cloned",
      number: 710,
      votes: 0,
    },
    {
      pic: require("./assets/amber.jpg"),
      name: "Amber Heard",
      partido: "The Anti-depp's",
      number: 400,
      votes: 0,
    },
    {
      pic: require("./assets/evilstrange.jpg"),
      name: "Evil Dr. Strange",
      partido: "Unlimited Powers Seekers",
      number: 666,
      votes: 0,
    },
  ],
};

export default candidates_list;
